### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Samshekar** [vuplex/xrit-webview-example#1] opened 2021-07-19 16:26 UTC
When webview on oculus quest we will get black canvas, in android works fine in debug mode. What will be the issue?

![com vuplex xritwebview-20210719-213546](https://user-images.githubusercontent.com/66861200/126192129-e40c492b-c78c-4561-a395-b6eb9ffbbf53.jpg)

**Comment by BinaryNate** [comment] 2021-07-19 19:28
Hi, @Samshekar 👋. Thank you for using 3D WebView! I really appreciate your business. To help me understand the issue, can you please tell me the following:

1. Which 3D WebView package are you using:
    a. [3D WebView for Android](https://store.vuplex.com/webview/android)
    b. [3D WebView for Android with Gecko Engine](https://store.vuplex.com/webview/android-gecko)

2. Are you experiencing this issue when you simply clone this repo and install 3D WebView? Or are you making other modifications to the project that are needed to reproduce the issue?

**Comment by Samshekar** [comment] 2021-07-27 07:28
I'm using  a. 3D WebView for the Android package. I have not done any modification, running an example scene.
Which is working fine without VR.

**Comment by BinaryNate** [comment] 2021-07-31 00:52
Thank you for the details, and sorry for my delayed response! I normally answer support questions via [the Vuplex contact page](https://support.vuplex.com/contact) and had forgotten to check GitHub for a few days. 

Oculus made a breaking change toward the start of the year that temporarily broke the ability of [3D WebView for Android](https://store.vuplex.com/webview/android) to render on Quest devices, but I published a fix for that in [v3.12](https://developer.vuplex.com/webview/releases) (released in April). So, I suspect you may be using an older version that predates the fix. Can you please try upgrading to the latest v3.13 release and check if that resolves the issue for you? If that doesn't resolve the issue, can you please email me (support@vuplex.com) a small example project that reproduces the issue?

Also, just a heads-up: for VR devices like Oculus Quest, I recommend using [3D WebView for Android with Gecko Engine](https://store.vuplex.com/webview/android-gecko). [This page](https://support.vuplex.com/articles/android-comparison) describes the differences between the two packages.

**Comment by BinaryNate** [comment] 2021-08-12 16:21
Closing this, since the issue seems to be resolved.

**Closed by BinaryNate** 2021-08-12 16:21 UTC
